name: "CI - Test Templates"
on:
  pull_request:
  push:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      templates: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            color: ./**/color/**
            hello: ./**/hello/**

  test:
    needs: [detect-changes]
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        templates: ${{ fromJSON(needs.detect-changes.outputs.templates) }}
    steps:
      - uses: actions/checkout@v4

      - uses: Jimver/cuda-toolkit@v0.2.27
        id: cuda-toolkit

      - name: Set Up Environment Variables
        run: |
          echo "UID=$(id -u)" >> $GITHUB_ENV
          echo "GPUS=0" >> $GITHUB_ENV
    

      - name: Smoke test for '${{ matrix.templates }}'
        id: smoke_test
        uses: ./.github/actions/smoke-test
        with:
          template: "${{ matrix.templates }}"
